name: mitoem2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adwaita-icon-theme=49.0=unix_0
  - affogato=0.4.2=py313hcce9d79_2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.2=h39aace5_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py313h7033f15_4
  - brunsli=0.1=he3183e4_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.21.3=h4cfbee9_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf46b229_1
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - coin-or-cbc=2.10.12=h4d16d09_4
  - coin-or-cgl=0.60.9=hc46dffc_6
  - coin-or-clp=1.17.10=hc03379b_3
  - coin-or-osi=0.108.11=hf4fecb4_7
  - coin-or-utils=2.11.12=hc93afbd_6
  - contourpy=1.3.3=py313h7037e92_2
  - cpython=3.13.9=py313hd8ed1ab_101
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.13.1.26=hbcb9cd8_0
  - cusparselt=0.7.0.0=hcd2ec93_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - epoxy=1.5.10=hb03c661_2
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - giflib=5.2.2=hd590300_0
  - glib=2.86.0=hbcf1ec1_1
  - glib-tools=2.86.0=hf516916_1
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h86d8783_1
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - gtk3=3.24.43=h993cebd_6
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.8.2=py313h718aa22_4
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.2.2=hde8ca8f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_1
  - kornia=0.8.1=pyhd8ed1ab_0
  - kornia-rs=0.1.9=py313h3073300_3
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lemon=1.3.1=h9457a4f_11
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.4=h3f801dc_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libboost=1.88.0=hed09d94_5
  - libboost-python=1.88.0=py313hfaae9d9_5
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=37_h0358290_openblas
  - libclang-cpp21.1=21.1.4=default_h99862b1_0
  - libclang13=21.1.4=default_h746c552_0
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.13.1.26=hf7e9902_0
  - libcudnn-dev=9.13.1.26=h58dd1b1_0
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h32235b2_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h6cb5226_4
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblapacke=3.9.0=37_h6ae95b6_openblas
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.4=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.8.0=h566cb83_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=hecca717_2
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=5.28.3=h6128344_1
  - librsvg=2.60.0=h61e6d4b_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libtorch=2.6.0=cuda126_generic_h4a15719_200
  - libudev1=257.9=h085a93f_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libvigra=1.12.2=h9404da8_6
  - libvorbis=1.3.7=h54a6638_2
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.2=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib=3.10.7=py313h78bf25f_0
  - matplotlib-base=3.10.7=py313h683a580_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - natsort=8.4.0=pyh29332c3_1
  - nccl=2.28.7.1=h4d09622_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - nifty=1.2.4=py313h19f269d_3
  - nomkl=1.0=h5ca1d4c_0
  - openexr=3.4.2=hff891e4_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.24.3=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - optree=0.17.0=py313h7037e92_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h08cd8bf_1
  - pango=1.56.4=hadf4263_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313ha492abd_3
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py313h85046ba_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.9=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py313h29aa505_1
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=60.0=hecca717_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-image=0.25.2=py313h08cd8bf_2
  - scikit-learn=1.7.2=py313h06d4379_0
  - scipy=1.16.2=py313h11c21cd_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hecca717_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py313h07c4f96_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vigra=1.12.2=hb4017ae_6
  - wayland=1.24.0=hd6090a7_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xarray=2025.10.1=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - zfp=1.0.1=h909a3a2_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py313h54dd161_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - acvl-utils==0.2.5
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - argparse==1.4.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - blosc2==3.10.2
      - click==8.3.0
      - cloudpickle==3.1.1
      - comm==0.2.3
      - connected-components-3d==3.26.0
      - connectomics==0.1
      - crc32c==2.8
      - cython==3.1.6
      - cztile==2.0.0
      - dask==2025.10.0
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - dicom2nifti==2.6.2
      - docstring-parser==0.17.0
      - donfig==0.8.1.post1
      - dynamic-network-architectures==0.3.1
      - einops==0.8.1
      - elf==0.7.3
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - fft-conv-pytorch==1.2.0
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - future==1.0.0
      - gputil==1.4.0
      - graphviz==0.21
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipykernel==7.1.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - lark==1.3.1
      - linecache2==1.0.0
      - llvmlite==0.45.1
      - locket==1.0.0
      - magicgui==0.10.1
      - markdown==3.9
      - micro-sam==1.6.0
      - mistune==3.1.4
      - monai==1.5.1
      - msgpack==1.1.2
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ndindex==1.10.0
      - nest-asyncio==1.6.0
      - nibabel==5.3.2
      - nnunetv2==2.5.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numcodecs==0.16.3
      - numexpr==2.14.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - pandocfilters==1.5.1
      - partd==1.4.2
      - prometheus-client==0.23.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - psygnal==0.15.0
      - py-cpuinfo==9.0.0
      - pyconify==0.2.1
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydicom==3.0.1
      - python-gdcm==3.2.2
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qtpy==2.4.3
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - seaborn==0.13.2
      - segment-anything==1.0
      - send2trash==1.8.3
      - simpleitk==2.5.2
      - simsimd==6.5.3
      - skan==0.13.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - stringzilla==4.2.3
      - superqt==0.7.6
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - toolz==1.1.0
      - torch==2.6.0+cu126
      - torch-em==0.7.12
      - torchvision==0.21.0+cu126
      - tqdm==4.67.1
      - traceback2==1.4.0
      - triton==3.2.0
      - typing-inspection==0.4.2
      - unittest2==1.1.0
      - uri-template==1.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xxhash==3.6.0
      - yacs==0.1.8
      - zarr==3.1.3
prefix: /projects/weilab/liupeng/conda/envs/mitoem2
